name: task_manager_app
description: Task Management App frontend
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  http: ^1.2.2
  intl: ^0.19.0
  uuid: ^4.5.1
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
